---
title: "False Positives in Mageck"
author: "Alex Kalinka"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    depth: 3
    highlight: tango
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
---

# Setup

```{r setup, include=FALSE}
set.seed(1)

options(warn=-1)
suppressMessages(library(knitr))
suppressMessages(library(tidyr))
suppressMessages(library(magrittr))
suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))
suppressMessages(library(seqgendiff))

data_root <- "~/data/az_cruk"

select <- dplyr::select
filter <- dplyr::filter
rename <- dplyr::rename


# Mageck false positive hits.
mfp <- read.table("~/data/az_cruk/ht29-francesco-iorio/01_Counts assembled/mfp-1.txt.gene_summary.txt", header=T, stringsAsFactors = F) %>%
  rowwise() %>%
  mutate(hit = (neg.p.value < 0.05 | pos.p.value < 0.05)) %>%
  ungroup()

# Normalized data.
load_normalised_counts <- function(path){
  load(path)
  return(normed)
}


path_ht29 <- file.path(data_root,"ht29-francesco-iorio","01_normalised_and_FCs")


# Assemble the sgRNAs, genes, and the two plasmid count replicates.
c903 <- load_normalised_counts(file.path(path_ht29,"HT29_c903.tsv_normCounts.RData"))
c904 <- load_normalised_counts(file.path(path_ht29,"HT29_c904.tsv_normCounts.RData"))
c905 <- load_normalised_counts(file.path(path_ht29,"HT29_c905.tsv_normCounts.RData"))
c906 <- load_normalised_counts(file.path(path_ht29,"HT29_c906.tsv_normCounts.RData"))
c907 <- load_normalised_counts(file.path(path_ht29,"HT29_c907.tsv_normCounts.RData"))
c908 <- load_normalised_counts(file.path(path_ht29,"HT29_c908.tsv_normCounts.RData"))

sgrna_comm <- Reduce(intersect, list(c903$sgRNA, c904$sgRNA, c905$sgRNA, c906$sgRNA, c907$sgRNA, c908$sgRNA))

c903 %<>% filter(sgRNA %in% sgrna_comm)
c904 %<>% filter(sgRNA %in% sgrna_comm)
c905 %<>% filter(sgRNA %in% sgrna_comm)
c906 %<>% filter(sgRNA %in% sgrna_comm)
c907 %<>% filter(sgRNA %in% sgrna_comm)
c908 %<>% filter(sgRNA %in% sgrna_comm)


expand_guides <- function(data){
  ret <- t(matrix(unlist(c(data[,3:4]),1,10)))
  ret <- t(apply(ret, 1, function(x) return(sort(x))))
  return(as.data.frame(ret))
}


# Get normalized reads ready for PCA.
process_reads <- function(data, control_1, control_2, treat_1, treat_2, numguides, norm=T){
  c1 <- sym(control_1); c2 <- sym(control_2); t1 <- sym(treat_1); t2 <- sym(treat_2)
  data %<>%
    select(sgRNA, gene, !!c1, !!c2, !!t1, !!t2)
  if(norm){
    # Library depth normalization.
    data %<>%
      mutate(mc1 = median(c(sum(!!c1),sum(!!c2),sum(!!t1),sum(!!t2))), 
             control.1 = mc1 * (!!c1)/sum(!!c1),
             control.2 = mc1 * (!!c2)/sum(!!c2),
             treat.1 = mc1 * (!!t1)/sum(!!t1),
             treat.2 = mc1 * (!!t2)/sum(!!t2)) %>%
      select(-mc1)
  }else{
    data %<>%
      rename(control.1 = !!c1, control.2 = !!c2,
             treat.1 = !!t1, treat.2 = !!t2)
  }
  # logFC for replicate pairs.
  data %<>%
    mutate(lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
    group_by(gene) %>%
    mutate(num_guides = n()) %>%
    filter(num_guides == numguides) %>%
    select(-num_guides,-control.1,-control.2,-treat.1,-treat.2) %>%
    do(data.frame(expand_guides(.))) %>%
    ungroup()
  return(data)
}


extract_pc2_optim <- function(data, prob){
  # top x% of abs(PC1) genes.
  cutoff <- quantile(abs(data$PC1),prob)
  genes <- data$gene[abs(data$PC1) >= cutoff]
  data %<>%
    arrange(PC2) %>%
    mutate(pc2_group = cut(PC2,70)) %>%
    group_by(pc2_group) %>%
    summarise(percent_top = 100*sum(gene %in% genes)/length(genes),
              PC2_median = median(PC2)) %>%
    ungroup() %>%
    mutate(percent_top.cumsum = cumsum(percent_top))
  return(data)
}

```

# Learn the PCA rotation matrix from 3 true negative datasets

```{r}
ht29.true_neg <- rbind(
  process_reads(c903, "HT29_c903R1","HT29_c903R2","HT29_c903R3","HT29_c903R4",numguides = 5,norm=F),
  process_reads(c905, "HT29_c905R1","HT29_c905R3","HT29_c905R2","HT29_c905R6",numguides = 5,norm=F),
  process_reads(c906, "HT29_c906R2","HT29_c906R7","HT29_c906R3","HT29_c906R8",numguides = 5,norm=F)
)


# Scale and center data so we diagonalize the correlation matrix instead of the covariance matrix.
pca.train <- prcomp(scale(ht29.true_neg[,2:11]))

ht29.true_neg %<>%
  mutate(PC1 = pca.train$x[,1], PC2 = pca.train$x[,2], PC3 = pca.train$x[,3], PC4 = pca.train$x[,4])

tn.cumsum <- extract_pc2_optim(ht29.true_neg, 0.99)

```

# Test untrained data

## True negatives

```{r}
test.tn_1 <- process_reads(c905, "HT29_c905R4","HT29_c905R5","HT29_c905R7","HT29_c905R9",numguides = 5,norm=F) %>%
  rowwise() %>%
  mutate(sd_logfc = sd(c(V1,V2,V3,V4,V5,V6,V7,V8,V9,V10),na.rm=T)) %>%
  ungroup()

base_norm_counts <- c905 %>%
  select(sgRNA,gene,HT29_c905R4,HT29_c905R5,HT29_c905R7,HT29_c905R9) %>%
  mutate(sd_logfc = test.tn_1$sd_logfc[match(gene,test.tn_1$gene)]) %>%
  filter(!is.na(sd_logfc)) %>%
  group_by(gene) %>%
  mutate(num_guides = n()) %>%
  ungroup() %>%
  filter(num_guides == 5) %>%
  mutate(HT29_c905R4 = round(HT29_c905R4), HT29_c905R5 = round(HT29_c905R5), 
         HT29_c905R7 = round(HT29_c905R7), HT29_c905R9 = round(HT29_c905R9))

rot.test.tn_1 <- as.data.frame(as.matrix(scale(test.tn_1[,2:11])) %*% pca.train$rotation)

test.tn_1 %<>%
  mutate(PC1 = rot.test.tn_1$PC1, PC2 = rot.test.tn_1$PC2, 
         PC3 = rot.test.tn_1$PC3, PC4 = rot.test.tn_1$PC4)

test.tn_1 %>%
  extract_pc2_optim(prob = 0.99) %>%
  ggplot(aes(PC2_median, percent_top.cumsum)) +
  geom_point() +
  geom_smooth()

```

## Signal added using `seqgendiff`

### Varying SD(logfc)

```{r}
# design matrix.
design_cols <- rep(0,4)
design_cols[3:4] <- 1
design_mat <- matrix(design_cols)

# Same signal added to gene sets with increasing SD(logfc).
num_sel_genes <- 200
lfc_signal <- rnorm(num_sel_genes,0,1)

# Low noise.
lfc_low <- lfc_signal
names(lfc_low) <- sample(base_norm_counts$gene[base_norm_counts$sd_logfc < 0.3], num_sel_genes)

coef_mat.low <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_low),
                                                           rep(lfc_low[names(lfc_low)==gene[1]],n()),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_low <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.low)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.low <- as.data.frame(as.matrix(scale(norm_low[,2:11])) %*% pca.train$rotation)

norm_low %<>%
  mutate(PC1 = rot.low$PC1, PC2 = rot.low$PC2, PC3 = rot.low$PC3, PC4 = rot.low$PC4)

# High noise.
lfc_high <- lfc_signal
names(lfc_high) <- sample(base_norm_counts$gene[base_norm_counts$sd_logfc > 0.4], num_sel_genes)

coef_mat.high <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_high),
                                                           rep(lfc_high[names(lfc_high)==gene[1]],n()),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_high <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.high)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.high <- as.data.frame(as.matrix(scale(norm_high[,2:11])) %*% pca.train$rotation)

norm_high %<>%
  mutate(PC1 = rot.high$PC1, PC2 = rot.high$PC2, PC3 = rot.high$PC3, PC4 = rot.high$PC4)


rbind(extract_pc2_optim(test.tn_1, prob = 0.99) %>%
        mutate(SD_lfc = "no_lfc"),
      extract_pc2_optim(norm_low, prob = 0.99) %>%
        mutate(SD_lfc = "low"),
      extract_pc2_optim(norm_high, prob = 0.99) %>%
        mutate(SD_lfc = "high")) %>%
  ggplot(aes(PC2_median, percent_top.cumsum, color = SD_lfc)) +
  geom_point() +
  geom_smooth() +
  xlim(-5,5)

```

### Varying number of guides with signal added

```{r}
# 1 guide with no signal.
coef_mat.low.m1 <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_low),
                                                           c(rep(lfc_low[names(lfc_low)==gene[1]],n()-1),0),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_low.m1 <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.low.m1)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.low.m1 <- as.data.frame(as.matrix(scale(norm_low.m1[,2:11])) %*% pca.train$rotation)

norm_low.m1 %<>%
  mutate(PC1 = rot.low.m1$PC1, PC2 = rot.low.m1$PC2, PC3 = rot.low.m1$PC3, PC4 = rot.low.m1$PC4)

# 2 guides with no signal.
coef_mat.low.m2 <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_low),
                                                           c(rep(lfc_low[names(lfc_low)==gene[1]],n()-2),0,0),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_low.m2 <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.low.m2)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.low.m2 <- as.data.frame(as.matrix(scale(norm_low.m2[,2:11])) %*% pca.train$rotation)

norm_low.m2 %<>%
  mutate(PC1 = rot.low.m2$PC1, PC2 = rot.low.m2$PC2, PC3 = rot.low.m2$PC3, PC4 = rot.low.m2$PC4)

# 3 guides with no signal.
coef_mat.low.m3 <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_low),
                                                           c(rep(lfc_low[names(lfc_low)==gene[1]],n()-3),0,0,0),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_low.m3 <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.low.m3)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.low.m3 <- as.data.frame(as.matrix(scale(norm_low.m3[,2:11])) %*% pca.train$rotation)

norm_low.m3 %<>%
  mutate(PC1 = rot.low.m3$PC1, PC2 = rot.low.m3$PC2, PC3 = rot.low.m3$PC3, PC4 = rot.low.m3$PC4)


# 4 guides with no signal.
coef_mat.low.m4 <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_low),
                                                           c(lfc_low[names(lfc_low)==gene[1]],0,0,0,0),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_low.m4 <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.low.m4)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.low.m4 <- as.data.frame(as.matrix(scale(norm_low.m4[,2:11])) %*% pca.train$rotation)

norm_low.m4 %<>%
  mutate(PC1 = rot.low.m4$PC1, PC2 = rot.low.m4$PC2, PC3 = rot.low.m4$PC3, PC4 = rot.low.m4$PC4)


rbind(extract_pc2_optim(norm_low, prob = 0.99) %>%
        mutate(nosig_count = "0"),
      extract_pc2_optim(norm_low.m1, prob = 0.99) %>%
        mutate(nosig_count = "1"),
      extract_pc2_optim(norm_low.m2, prob = 0.99) %>%
        mutate(nosig_count = "2"),
      extract_pc2_optim(norm_low.m3, prob = 0.99) %>%
        mutate(nosig_count = "3"),
      extract_pc2_optim(norm_low.m4, prob = 0.99) %>%
        mutate(nosig_count = "4")) %>%
  ggplot(aes(PC2_median, percent_top.cumsum, color = nosig_count)) +
  geom_point() +
  geom_smooth()

```

### Varying prevalence

```{r}
# 100 genes
num_sel_genes <- 100
lfc_signal <- rnorm(num_sel_genes,0,1)


lfc_100 <- lfc_signal
names(lfc_100) <- sample(base_norm_counts$gene[between(base_norm_counts$sd_logfc,0.325,0.375)], num_sel_genes)

coef_mat.100 <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_100),
                                                           rep(lfc_100[names(lfc_100)==gene[1]],n()),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_100 <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.100)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.100 <- as.data.frame(as.matrix(scale(norm_100[,2:11])) %*% pca.train$rotation)

norm_100 %<>%
  mutate(PC1 = rot.100$PC1, PC2 = rot.100$PC2, PC3 = rot.100$PC3, PC4 = rot.100$PC4)


# 500 genes.
num_sel_genes <- 500
lfc_signal <- rnorm(num_sel_genes,0,1)


lfc_500 <- lfc_signal
names(lfc_500) <- sample(base_norm_counts$gene[between(base_norm_counts$sd_logfc,0.325,0.375)], num_sel_genes)

coef_mat.500 <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_500),
                                                           rep(lfc_500[names(lfc_500)==gene[1]],n()),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_500 <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.500)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.500 <- as.data.frame(as.matrix(scale(norm_500[,2:11])) %*% pca.train$rotation)

norm_500 %<>%
  mutate(PC1 = rot.500$PC1, PC2 = rot.500$PC2, PC3 = rot.500$PC3, PC4 = rot.500$PC4)


# 1000 genes.
num_sel_genes <- 1000
lfc_signal <- rnorm(num_sel_genes,0,1)


lfc_1000 <- lfc_signal
names(lfc_1000) <- sample(base_norm_counts$gene[between(base_norm_counts$sd_logfc,0.325,0.375)], num_sel_genes)

coef_mat.1000 <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_1000),
                                                           rep(lfc_1000[names(lfc_1000)==gene[1]],n()),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_1000 <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.1000)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.1000 <- as.data.frame(as.matrix(scale(norm_1000[,2:11])) %*% pca.train$rotation)

norm_1000 %<>%
  mutate(PC1 = rot.1000$PC1, PC2 = rot.1000$PC2, PC3 = rot.1000$PC3, PC4 = rot.1000$PC4)


rbind(extract_pc2_optim(norm_100, prob = 0.99) %>%
        mutate(num_sel = "100"),
      extract_pc2_optim(norm_500, prob = 0.99) %>%
        mutate(num_sel = "500"),
      extract_pc2_optim(norm_1000, prob = 0.99) %>%
        mutate(num_sel = "1000"),
      extract_pc2_optim(test.tn_1, prob = 0.99) %>%
        mutate(num_sel = "0")) %>%
  ggplot(aes(PC2_median, percent_top.cumsum, color = num_sel)) +
  geom_point() +
  geom_smooth()

```

### Varying magnitude of logfc

```{r}
# lfc 1.
num_sel_genes <- 200
lfc_signal <- rep(1,num_sel_genes)


lfc_l1 <- lfc_signal
names(lfc_l1) <- names(lfc_low)

coef_mat.l1 <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_l1),
                                                           rep(lfc_l1[names(lfc_l1)==gene[1]],n()),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_l1 <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.l1)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.l1 <- as.data.frame(as.matrix(scale(norm_l1[,2:11])) %*% pca.train$rotation)

norm_l1 %<>%
  mutate(PC1 = rot.l1$PC1, PC2 = rot.l1$PC2, PC3 = rot.l1$PC3, PC4 = rot.l1$PC4)


# lfc 2.
num_sel_genes <- 200
lfc_signal <- rep(2,num_sel_genes)


lfc_l2 <- lfc_signal
names(lfc_l2) <- names(lfc_low)

coef_mat.l2 <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_l2),
                                                           rep(lfc_l2[names(lfc_l2)==gene[1]],n()),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_l2 <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.l2)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.l2 <- as.data.frame(as.matrix(scale(norm_l2[,2:11])) %*% pca.train$rotation)

norm_l2 %<>%
  mutate(PC1 = rot.l2$PC1, PC2 = rot.l2$PC2, PC3 = rot.l2$PC3, PC4 = rot.l2$PC4)


# lfc 3.
num_sel_genes <- 200
lfc_signal <- rep(3,num_sel_genes)


lfc_l3 <- lfc_signal
names(lfc_l3) <- names(lfc_low)

coef_mat.l3 <- as.matrix(base_norm_counts %>%
                            group_by(gene) %>%
                            mutate(gene_indicator = ifelse(gene %in% names(lfc_l3),
                                                           rep(lfc_l3[names(lfc_l3)==gene[1]],n()),
                                                           rep(0,n()))) %>%
                            ungroup() %>%
                            select(gene_indicator))

norm_l3 <- as.data.frame(thin_diff(mat = as.matrix(base_norm_counts[,3:6]), 
                   design_fixed = design_mat, 
                   coef_fixed = coef_mat.l3)$mat) %>%
  rename(control.1 = V1, control.2 = V2, treat.1 = V3, treat.2 = V4) %>%
  mutate(gRNA = base_norm_counts$sgRNA, gene = base_norm_counts$gene,
         lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  group_by(gene) %>%
  select(-control.1,-control.2,-treat.1,-treat.2) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rot.l3 <- as.data.frame(as.matrix(scale(norm_l3[,2:11])) %*% pca.train$rotation)

norm_l3 %<>%
  mutate(PC1 = rot.l3$PC1, PC2 = rot.l3$PC2, PC3 = rot.l3$PC3, PC4 = rot.l3$PC4)


rbind(extract_pc2_optim(norm_l1, prob = 0.99) %>%
        mutate(lfc = "1"),
      extract_pc2_optim(norm_l2, prob = 0.99) %>%
        mutate(lfc = "2"),
      extract_pc2_optim(norm_l3, prob = 0.99) %>%
        mutate(lfc = "3"),
      extract_pc2_optim(test.tn_1, prob = 0.99) %>%
        mutate(lfc = "0")) %>%
  ggplot(aes(PC2_median, percent_top.cumsum, color = lfc)) +
  geom_point() +
  geom_smooth()


```



# Real screen data

```{r}
# UAT bthin for true LFC.
bb <- readRDS(file="/Users/alexkalinka/git-projects/fgc_crispr_pipeline_UAT/data/bthin_lfc_rnorm.rds")
bb <- bb[abs(bb) > 1]
vv <- read.table("/Users/alexkalinka/git-projects/fgc_crispr_pipeline_UAT/data/combined_counts/dataset/bthin_from_combinedcounts/c903-bthin-rnorm.500.symmFC.txt",header=T,stringsAsFactors = F) %>%
  select(-YUSAplasmid,-YUSADMSOD0) %>%
  mutate(mc1 = median(c(sum(control.1),sum(control.2),sum(treat.1),sum(treat.2))), 
         control.1 = mc1 * control.1/sum(control.1),
         control.2 = mc1 * control.2/sum(control.2),
         treat.1 = mc1 * treat.1/sum(treat.1),
         treat.2 = mc1 * treat.2/sum(treat.2)) %>%
  rowwise() %>%
  mutate(lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  ungroup() %>%
  group_by(gene) %>%
  mutate(num_guides = n()) %>%
  filter(num_guides == 5) %>%
  select(-num_guides,-control.1,-control.2,-treat.1,-treat.2,-mc1) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rr1 <- as.data.frame(as.matrix(scale(vv[,2:11])) %*% pca.train$rotation)

vv %<>%
  mutate(PC1 = rr1$PC1, PC2 = rr1$PC2, PC3 = rr1$PC3, PC4 = rr1$PC4)
  
# fgc_0005.
# SW480.
tt <- read.csv("~/data/az_cruk/cdc7/fgc_0005_depletion_hit_table.csv",stringsAsFactors = F)

ww_hits <- read.table("/Users/alexkalinka/data/az_cruk/cdc7/Comp-SW480/mageck/Treatment_vs_Control.gene_summary.txt",
                      header=T, stringsAsFactors = F) %>%
  rowwise() %>%
  mutate(hit = (neg.p.value < 0.05 | pos.p.value < 0.05)) %>%
  ungroup()
ww <- read.table("/Users/alexkalinka/data/az_cruk/cdc7/Comp-SW480/counts/combined_counts.txt",
                 header=T, stringsAsFactors = F) %>%
  select(-FGC0005_01_03_01,-FGC0005_01_03_02,-Yusa_v3_KO_Plasmid_FGC_batch_1) %>%
  mutate(mc1 = median(c(sum(FGC0005_01_03_03),sum(FGC0005_01_03_04),sum(FGC0005_01_03_05),sum(FGC0005_01_03_06))), 
         control.1 = mc1 * FGC0005_01_03_03/sum(FGC0005_01_03_03),
         control.2 = mc1 * FGC0005_01_03_04/sum(FGC0005_01_03_04),
         treat.1 = mc1 * FGC0005_01_03_05/sum(FGC0005_01_03_05),
         treat.2 = mc1 * FGC0005_01_03_06/sum(FGC0005_01_03_06)) %>%
  rowwise() %>%
  mutate(lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  ungroup() %>%
  group_by(gene) %>%
  mutate(num_guides = n()) %>%
  filter(num_guides == 6 & !grepl("-6$",sgRNA)) %>%
  select(-num_guides,-control.1,-control.2,-treat.1,-treat.2,-mc1,
         -FGC0005_01_03_03,-FGC0005_01_03_04,-FGC0005_01_03_05,-FGC0005_01_03_06) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rr2 <- as.data.frame(as.matrix(scale(ww[,2:11])) %*% pca.train$rotation)

ww %<>%
  mutate(PC1 = rr2$PC1, PC2 = rr2$PC2, PC3 = rr2$PC3, PC4 = rr2$PC4)


# RKO.
kk <- read.table("/Users/alexkalinka/data/az_cruk/cdc7/Comp-RKO/counts/combined_counts.txt",
                 header=T, stringsAsFactors = F) %>%
  select(-FGC0005_01_02_01,-FGC0005_01_02_02,-Yusa_v3_KO_Plasmid_FGC_batch_1) %>%
  mutate(mc1 = median(c(sum(FGC0005_01_02_03),sum(FGC0005_01_02_04),sum(FGC0005_01_02_05),sum(FGC0005_01_02_06))), 
         control.1 = mc1 * FGC0005_01_02_03/sum(FGC0005_01_02_03),
         control.2 = mc1 * FGC0005_01_02_04/sum(FGC0005_01_02_04),
         treat.1 = mc1 * FGC0005_01_02_05/sum(FGC0005_01_02_05),
         treat.2 = mc1 * FGC0005_01_02_06/sum(FGC0005_01_02_06)) %>%
  rowwise() %>%
  mutate(lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  ungroup() %>%
  group_by(gene) %>%
  mutate(num_guides = n()) %>%
  filter(num_guides == 6 & !grepl("-6$",sgRNA)) %>%
  select(-num_guides,-control.1,-control.2,-treat.1,-treat.2,-mc1,
         -FGC0005_01_02_03,-FGC0005_01_02_04,-FGC0005_01_02_05,-FGC0005_01_02_06) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rr3 <- as.data.frame(as.matrix(scale(kk[,2:11])) %*% pca.train$rotation)

kk %<>%
  mutate(PC1 = rr3$PC1, PC2 = rr3$PC2, PC3 = rr3$PC3, PC4 = rr3$PC4)


# HCT116.
cc <- read.table("/Users/alexkalinka/data/az_cruk/cdc7/Comp-HCT116/counts/combined_counts.txt",
                 header=T, stringsAsFactors = F) %>%
  select(-FGC0005_01_04_01,-FGC0005_01_04_02,-FGC0005_01_04_03,
         -FGC0005_01_04_06,-FGC0005_01_04_09,-Yusa_v3_KO_Plasmid_FGC_batch_1) %>%
  mutate(mc1 = median(c(sum(FGC0005_01_04_04),sum(FGC0005_01_04_05),
                        sum(FGC0005_01_04_07),sum(FGC0005_01_04_08))), 
         control.1 = mc1 * FGC0005_01_04_04/sum(FGC0005_01_04_04),
         control.2 = mc1 * FGC0005_01_04_05/sum(FGC0005_01_04_05),
         treat.1 = mc1 * FGC0005_01_04_07/sum(FGC0005_01_04_07),
         treat.2 = mc1 * FGC0005_01_04_08/sum(FGC0005_01_04_08)) %>%
  rowwise() %>%
  mutate(lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  ungroup() %>%
  group_by(gene) %>%
  mutate(num_guides = n()) %>%
  filter(num_guides == 6 & !grepl("-6$",sgRNA)) %>%
  select(-num_guides,-control.1,-control.2,-treat.1,-treat.2,-mc1,
         -FGC0005_01_04_04,-FGC0005_01_04_05,-FGC0005_01_04_07,-FGC0005_01_04_08) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rr4 <- as.data.frame(as.matrix(scale(cc[,2:11])) %*% pca.train$rotation)

cc %<>%
  mutate(PC1 = rr4$PC1, PC2 = rr4$PC2, PC3 = rr4$PC3, PC4 = rr4$PC4)


# HT29
uu <- read.table("/Users/alexkalinka/data/az_cruk/cdc7/Comp-HT-29/counts/combined_counts.txt",
                 header=T, stringsAsFactors = F) %>%
  select(-FGC0005_01_01_01,-FGC0005_01_01_02,-Yusa_v3_KO_Plasmid_FGC_batch_1) %>%
  mutate(mc1 = median(c(sum(FGC0005_01_01_03),sum(FGC0005_01_01_04),sum(FGC0005_01_01_05),sum(FGC0005_01_01_06))), 
         control.1 = mc1 * FGC0005_01_01_03/sum(FGC0005_01_01_03),
         control.2 = mc1 * FGC0005_01_01_04/sum(FGC0005_01_01_04),
         treat.1 = mc1 * FGC0005_01_01_05/sum(FGC0005_01_01_05),
         treat.2 = mc1 * FGC0005_01_01_06/sum(FGC0005_01_01_06)) %>%
  rowwise() %>%
  mutate(lfc.1 = log2((control.1+5)/(treat.1+5)), 
         lfc.2 = log2((control.2+5)/(treat.2+5))) %>%
  ungroup() %>%
  group_by(gene) %>%
  mutate(num_guides = n()) %>%
  filter(num_guides == 6 & !grepl("-6$",sgRNA)) %>%
  select(-num_guides,-control.1,-control.2,-treat.1,-treat.2,-mc1,
         -FGC0005_01_01_03,-FGC0005_01_01_04,-FGC0005_01_01_05,-FGC0005_01_01_06) %>%
  do(data.frame(expand_guides(.))) %>%
  ungroup()

rr5 <- as.data.frame(as.matrix(scale(uu[,2:11])) %*% pca.train$rotation)

uu %<>%
  mutate(PC1 = rr5$PC1, PC2 = rr5$PC2, PC3 = rr5$PC3, PC4 = rr5$PC4)


```

```{r}
rbind(extract_pc2_optim(kk, prob = 0.99) %>%
        mutate(cell_line = "RKO"),
      extract_pc2_optim(cc, prob = 0.99) %>%
        mutate(cell_line = "HCT116"),
      extract_pc2_optim(ww, prob = 0.99) %>%
        mutate(cell_line = "SW480"),
      extract_pc2_optim(uu, prob = 0.99) %>%
        mutate(cell_line = "HT29")) %>%
  ggplot(aes(PC2_median, percent_top.cumsum, color = cell_line)) +
  geom_point() +
  geom_smooth() +
  xlim(-2,10)

```

