---
title: "Mock QC data for evaluating QC dahsboard solution: AWS Quicksight vs powerBI"
author: "Alex Kalinka"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    depth: 3
    highlight: tango
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
---

# Setup

```{r setup}
set.seed(1)

options(warn=-1)
suppressMessages(library(knitr))
suppressMessages(library(tidyr))
suppressMessages(library(magrittr))
suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))
suppressMessages(library(digest))

```

# Approach

* 200 flowcells with 20 samples each over 3.9 years.
* Columns to the left of the `sample` column are experiment-level variables, to the right are sample-level.
* Data is simulated by sampling from distributions with the expected properties of the real data.

# Data

## Generation

```{r}
num_exp <- 200
flowcells <- paste("H",substr(sapply(1:num_exp, function(x) digest(rnorm(100), algo = "md5")),1,6),sep="")
dates <- sort(sample(seq(as.Date("2020/02/18"), as.Date("2024/01/01"), by="day"), num_exp))

data <- data.frame(flowcell = flowcells, 
                   run_date = dates,
                   reads_passing_filter_percent = 100*rbeta(num_exp,7,1),
                   total_q30_bases_percent = 100*rbeta(num_exp,8,2),
                   non_demultiplexed_reads_percent = 100*rbeta(num_exp,1.3,6.9)) %>%
  left_join(data.frame(flowcell = rep(flowcells, each=5),
                       screen = rep(1:5,num_exp/5)) %>%
              group_by(flowcell, screen) %>%
              mutate(GICC = rbeta(n(),6.5,3),
                     glass_delta_logfc = rnorm(n(),2,0.5),
                     auroc = rbeta(n(),9.1,1.2),
                     auprrc = rbeta(n(),7.5,3.5),
                     nmmd = rnorm(n(),1.2,0.5)),
            by = "flowcell") %>%
  left_join(data.frame(flowcell = rep(flowcells, each=20),
                       screen = rep(1:5,each=4)) %>%
              group_by(flowcell, screen) %>%
              mutate(sample = paste("S",1:n(),sep=""),
                     dna_quant = rgamma(n(),0.65,0.3),
                     sample_representation_percent = 100*rbeta(n(),0.1,1.9),
                     matching_grna_reads_percent = 100*rbeta(n(),5,2),
                     zero_count_plasmid_percent = 100*rbeta(n(),0.07,2),
                     grna_gc_regression = rnorm(n(),0.1,0.8),
                     gini_coefficient = rbeta(n(),2,2)) %>%
              ungroup() %>%
              mutate(sample = rep(paste("S",1:20,sep=""),num_exp)),
            by = c("flowcell","screen"))


write.csv(data,file="../data/mock_fgc_qc_data.csv", quote=F, col.names = T,row.names = F)

```

## Examples

```{r}
ggplot(data, aes(run_date, reads_passing_filter_percent)) +
  geom_point() +
  geom_line() +
  scale_x_date() +
  ggtitle("Reads Passing Filter (%) by run date")

ggplot(data, aes(auroc)) +
  geom_density(fill = "palegoldenrod") +
  ggtitle("AUROC")

ggplot(data, aes(auprrc)) +
  geom_density(fill = "palegoldenrod") +
  ggtitle("AU Precision-Recall")

```


